alchemy:
  api_key: ${ALCHEMY_API_KEY}
  enabled: true
  rate_limit: 100
api_keys:
  alchemy: ${ALCHEMY_API_KEY}
  ankr: ${ANKR_API_KEY}
  blastapi: ${BLASTAPI_API_KEY}
  coingecko: ${COINGECKO_API_KEY}
  drpc: ${DRPC_API_KEY}
contracts:
  erc20_abi:
  - name: name
    outputs:
    - name: ''
      type: string
    stateMutability: view
    type: function
  - name: symbol
    outputs:
    - name: ''
      type: string
    stateMutability: view
    type: function
  - name: decimals
    outputs:
    - name: ''
      type: uint8
    stateMutability: view
    type: function
  - name: totalSupply
    outputs:
    - name: ''
      type: uint256
    stateMutability: view
    type: function
  - inputs:
    - name: account
      type: address
    name: balanceOf
    outputs:
    - name: ''
      type: uint256
    stateMutability: view
    type: function
  - inputs:
    - name: to
      type: address
    - name: amount
      type: uint256
    name: transfer
    outputs:
    - name: ''
      type: bool
    stateMutability: nonpayable
    type: function
  - inputs:
    - name: owner
      type: address
    - name: spender
      type: address
    name: allowance
    outputs:
    - name: ''
      type: uint256
    stateMutability: view
    type: function
  - inputs:
    - name: spender
      type: address
    - name: amount
      type: uint256
    name: approve
    outputs:
    - name: ''
      type: bool
    stateMutability: nonpayable
    type: function
  - inputs:
    - name: from
      type: address
    - name: to
      type: address
    - name: amount
      type: uint256
    name: transferFrom
    outputs:
    - name: ''
      type: bool
    stateMutability: nonpayable
    type: function
  uniswap_v2_factory_abi:
  - inputs:
    - name: tokenA
      type: address
    - name: tokenB
      type: address
    name: getPair
    outputs:
    - name: pair
      type: address
    stateMutability: view
    type: function
  - inputs:
    - name: token0
      type: address
    - name: token1
      type: address
    name: getPair
    outputs:
    - name: pair
      type: address
    stateMutability: view
    type: function
  uniswap_v2_pair_abi:
  - inputs: []
    name: getReserves
    outputs:
    - name: _reserve0
      type: uint112
    - name: _reserve1
      type: uint112
    - name: _blockTimestampLast
      type: uint32
    stateMutability: view
    type: function
  - inputs: []
    name: token0
    outputs:
    - name: ''
      type: address
    stateMutability: view
    type: function
  - inputs: []
    name: token1
    outputs:
    - name: ''
      type: address
    stateMutability: view
    type: function
  - inputs: []
    name: totalSupply
    outputs:
    - name: ''
      type: uint256
    stateMutability: view
    type: function
ethereum:
  chain_id: 1
  chainlist:
    cache_duration_hours: 168
    cached_providers: 20
    last_updated: '2025-09-17T14:33:32.760434'
    max_providers: 20
    refresh_on_startup: true
    total_providers: 20
    url: https://chainlist.org/rpcs.json
  gas_limit: 100000
  ignore_list:
    auto_clear_on_refresh: true
    duration_hours: 24
  load_balancing:
    health_check_interval: 60
    max_concurrent_requests: 5
    retry_attempts: 3
    retry_delay: 1
    strategy: round_robin
monitoring:
  export_format:
  - json
  - csv
  historical_data_days: 30
  log_level: INFO
  price_update_interval: 3600
pools:
  uniswap_v2_factory: 0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f
  uniswap_v3_factory: 0x1F98431c8aD98523631AE4a59f267346ea31F984
  weth_address: 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
price_sources:
  coingecko:
    api_key: ${COINGECKO_API_KEY}
    enabled: true
    rate_limit: 50
  dexscreener:
    enabled: true
    rate_limit: 30
  oneinch:
    enabled: true
    rate_limit: 20
  uniswap:
    enabled: true
    rate_limit: 100
roko_token:
  address: 634460209752492759150162917838696066195990839192
  decimals: 18
  name: ROKO
  symbol: ROKO
  uniswap_pair: 1278979549828856515201214564315408281080422456062
