ethereum:
  # Primary RPC providers (will be used in order with failover)
  rpc_providers:
    - name: "eth.llamarpc"
      url: "https://eth.llamarpc.com"
      api_key: ""
      priority: 1
      rate_limit: 100  # requests per minute
      timeout: 30
    - name: "blxr-virginia"
      url: "https://virginia.rpc.blxrbdn.com"
      api_key: ""
      priority: 2
      rate_limit: 200
      timeout: 30
    - name: "blxr-eth"
      url: "https://eth.rpc.blxrbdn.com"
      api_key: ""
      priority: 3
      rate_limit: 200
      timeout: 30
    - name: "drpc"
      url: "https://eth.drpc.org"
      api_key: "${DRPC_API_KEY}"
      priority: 4
      rate_limit: 150
      timeout: 30
    - name: "poolz"
      url: "https://rpc.poolz.finance/eth"
      api_key: ""
      priority: 5
      rate_limit: 100
      timeout: 30
    - name: "blastapi"
      url: "https://eth-mainnet.public.blastapi.io"
      api_key: "${BLASTAPI_API_KEY}"
      priority: 6
      rate_limit: 100
      timeout: 30
    - name: "blockrazor"
      url: "https://eth.blockrazor.xyz"
      api_key: "${BLOCKRAZOR_API_KEY}"
      priority: 7
      rate_limit: 100
      timeout: 30
    - name: "alchemy"
      url: "https://eth-mainnet.g.alchemy.com/v2/{API_KEY}"
      api_key: "${ALCHEMY_API_KEY}"
      priority: 8
      rate_limit: 1000
      timeout: 30
    - name: "infura"
      url: "https://mainnet.infura.io/v3/{API_KEY}"
      api_key: "${INFURA_API_KEY}"
      priority: 9
      rate_limit: 1000
      timeout: 30
    - name: "public"
      url: "https://ethereum.publicnode.com"
      api_key: ""
      priority: 10
      rate_limit: 50
      timeout: 30
  
  # Legacy single RPC (for backward compatibility)
  rpc_url: "https://eth.llamarpc.com"
  api_key: ""
  
  # Chain configuration
  chain_id: 1
  gas_limit: 100000
  
  # Load balancing settings
  load_balancing:
    strategy: "round_robin"  # round_robin, priority, random
    retry_attempts: 3
    retry_delay: 1  # seconds
    health_check_interval: 60  # seconds
    max_concurrent_requests: 5

roko_token:
  address: "0x6f222e04f6c53cc688ffb0abe7206aac66a8ff98"
  name: "ROKO"
  symbol: "ROKO"

monitoring:
  update_interval: 30  # seconds
  historical_data_days: 30
  export_format: ["json", "csv"]
  log_level: "INFO"

pools:
  uniswap_v2_factory: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
  uniswap_v3_factory: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
  weth_address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  usdc_address: "0xA0b86a33E6441b8C4C8C0C4C8C0C4C8C0C4C8C0C4"

contracts:
  erc20_abi:
    - type: "function"
      name: "name"
      stateMutability: "view"
      outputs:
        - type: "string"
          name: ""
    - type: "function"
      name: "symbol"
      stateMutability: "view"
      outputs:
        - type: "string"
          name: ""
    - type: "function"
      name: "decimals"
      stateMutability: "view"
      outputs:
        - type: "uint8"
          name: ""
    - type: "function"
      name: "totalSupply"
      stateMutability: "view"
      outputs:
        - type: "uint256"
          name: ""
    - type: "function"
      name: "balanceOf"
      stateMutability: "view"
      inputs:
        - type: "address"
          name: "account"
      outputs:
        - type: "uint256"
          name: ""
    - type: "function"
      name: "transfer"
      stateMutability: "nonpayable"
      inputs:
        - type: "address"
          name: "to"
        - type: "uint256"
          name: "amount"
      outputs:
        - type: "bool"
          name: ""
    - type: "function"
      name: "allowance"
      stateMutability: "view"
      inputs:
        - type: "address"
          name: "owner"
        - type: "address"
          name: "spender"
      outputs:
        - type: "uint256"
          name: ""
    - type: "function"
      name: "approve"
      stateMutability: "nonpayable"
      inputs:
        - type: "address"
          name: "spender"
        - type: "uint256"
          name: "amount"
      outputs:
        - type: "bool"
          name: ""
    - type: "function"
      name: "transferFrom"
      stateMutability: "nonpayable"
      inputs:
        - type: "address"
          name: "from"
        - type: "address"
          name: "to"
        - type: "uint256"
          name: "amount"
      outputs:
        - type: "bool"
          name: ""
    - type: "event"
      name: "Transfer"
      inputs:
        - type: "address"
          name: "from"
          indexed: true
        - type: "address"
          name: "to"
          indexed: true
        - type: "uint256"
          name: "value"
          indexed: false
    - type: "event"
      name: "Approval"
      inputs:
        - type: "address"
          name: "owner"
          indexed: true
        - type: "address"
          name: "spender"
          indexed: true
        - type: "uint256"
          name: "value"
          indexed: false

  uniswap_v2_pair_abi:
    - type: "function"
      name: "getReserves"
      stateMutability: "view"
      outputs:
        - type: "uint112"
          name: "reserve0"
        - type: "uint112"
          name: "reserve1"
        - type: "uint32"
          name: "blockTimestampLast"
    - type: "function"
      name: "token0"
      stateMutability: "view"
      outputs:
        - type: "address"
          name: ""
    - type: "function"
      name: "token1"
      stateMutability: "view"
      outputs:
        - type: "address"
          name: ""
    - type: "function"
      name: "totalSupply"
      stateMutability: "view"
      outputs:
        - type: "uint256"
          name: ""
    - type: "function"
      name: "kLast"
      stateMutability: "view"
      outputs:
        - type: "uint256"
          name: ""
    - type: "event"
      name: "Swap"
      inputs:
        - type: "address"
          name: "sender"
          indexed: true
        - type: "uint256"
          name: "amount0In"
          indexed: false
        - type: "uint256"
          name: "amount1In"
          indexed: false
        - type: "uint256"
          name: "amount0Out"
          indexed: false
        - type: "uint256"
          name: "amount1Out"
          indexed: false
        - type: "address"
          name: "to"
          indexed: true
    - type: "event"
      name: "Sync"
      inputs:
        - type: "uint112"
          name: "reserve0"
          indexed: false
        - type: "uint112"
          name: "reserve1"
          indexed: false

  uniswap_v2_factory_abi:
    - type: "function"
      name: "getPair"
      stateMutability: "view"
      inputs:
        - type: "address"
          name: "tokenA"
        - type: "address"
          name: "tokenB"
      outputs:
        - type: "address"
          name: "pair"
    - type: "function"
      name: "allPairs"
      stateMutability: "view"
      inputs:
        - type: "uint256"
          name: "index"
      outputs:
        - type: "address"
          name: "pair"
    - type: "function"
      name: "allPairsLength"
      stateMutability: "view"
      outputs:
        - type: "uint256"
          name: "length"
    - type: "event"
      name: "PairCreated"
      inputs:
        - type: "address"
          name: "token0"
          indexed: true
        - type: "address"
          name: "token1"
          indexed: true
        - type: "address"
          name: "pair"
          indexed: false
        - type: "uint256"
          name: "index"
          indexed: false

